FROM patchworkdocker

RUN pip --disable-pip-version-check install -U coverage

ADD test-requirements.txt /tmp/test-requirements.txt
RUN pip install -r /tmp/test-requirements.txt

ENTRYPOINT []
CMD ["./run-tests.sh"]
